version: '3'
services:
    squid:
        container_name: squid
        image: misterbabou/squid:latest
        restart: unless-stopped
        ports:
            - 3128:3128
        volumes:
            - ./conf:/conf
            - ./cache:/var/spool/squid
            - ./log:/var/log/squid

