name: Publish Docker AMD64 Image

on:
  push:
    tags:
      - '*'  # Déclencheur pour les tags versionnés

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Extract tag name
        run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV

      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/squid:${{ env.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/squid:latest
